services:
  ui-web:
    build:
      context: ../..
      dockerfile: apps/ui-web/Dockerfile
    container_name: prospectflow-ui-web
    ports:
      - '4000:4000'
    env_file:
      - ./env/.env.${APP_ENV:-production}
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:4000/']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - net_private

networks:
  net_private:
    external: true
    name: net_private
