services:
  prospectflow-ingest-api:
    image: starlightcoder/prospectflow-ingest-api:latest
    container_name: prospectflow-ingest-api
    build:
      context: ../..
      dockerfile: apps/ingest-api/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./env/.env.production
    restart: unless-stopped
    networks:
      - prospectflow-network

networks:
  prospectflow-network:
    external: true
    name: prospectflow-network
