services:
  redis:
    image: redis:7-alpine
    container_name: prospectflow-redis
    hostname: redis
    restart: unless-stopped
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf --requirepass \"$${REDIS_PASSWORD}\""
    env_file:
      - .env.production
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - prospectflow-network

networks:
  prospectflow-network:
    external: true
    name: prospectflow-network
